from dataclasses import dataclass
import cv2
import numpy as np
from ..config import Settings
from ..models import TemplateMetadata, QuestionResult

CHOICES = "ABCDEFGH"


@dataclass
class Grid:
    rows_per_column: int
    columns: int
    start_x: float
    start_y: float
    row_step: float
    column_step: float
    question_label_width: float
    choice_step: float


def build_grid(template: TemplateMetadata) -> Grid:
    columns = template.columns or max(1, min(4, int(np.ceil(template.questions_count / 25))))
    rows = int(np.ceil(template.questions_count / columns))
    # Matches the normalized A4 geometry generated by src/lib/bubble-sheet.ts.
    row_width_mm = 12 + template.choices_count * 10 + 4
    column_step = row_width_mm / 210.0
    return Grid(rows, columns, 15 / 210, 55 / 297, 8 / 297, column_step, 12 / 210, 10 / 210)


def _fill(binary: np.ndarray, cx: int, cy: int, radius: int) -> float:
    mask = np.zeros(binary.shape, dtype=np.uint8)
    cv2.circle(mask, (cx, cy), max(2, radius), 255, -1)
    pixels = binary[mask == 255]
    return float((pixels > 0).mean()) if pixels.size else 0.0


def detect_bubbles(binary: np.ndarray, template: TemplateMetadata, settings: Settings) -> list[QuestionResult]:
    height, width = binary.shape[:2]
    grid = build_grid(template)
    results: list[QuestionResult] = []
    for q in range(template.questions_count):
        column = q // grid.rows_per_column
        row = q % grid.rows_per_column
        x0 = grid.start_x + column * grid.column_step
        y = grid.start_y + row * grid.row_step
        scores: dict[str, float] = {}
        boxes: dict[str, list[int]] = {}
        for idx in range(template.choices_count):
            label = CHOICES[idx]
            x = x0 + grid.question_label_width + idx * grid.choice_step + grid.choice_step / 2
            cx, cy = int(x * width), int(y * height)
            radius = max(3, int(grid.choice_step * width * 0.32))
            scores[label] = round(_fill(binary, cx, cy, radius), 4)
            boxes[label] = [cx - radius, cy - radius, cx + radius, cy + radius]
        ordered = sorted(scores.items(), key=lambda item: item[1], reverse=True)
        best_label, best = ordered[0]
        second = ordered[1][1] if len(ordered) > 1 else 0.0
        marked = [label for label, score in ordered if score >= settings.minimum_mark_fill]
        warnings: list[str] = []
        if not marked or best < settings.blank_threshold:
            status = "blank"
            detected = None
            confidence = max(0.0, min(1.0, 1 - best / max(settings.blank_threshold, 0.01)))
        elif len(marked) > 1 and best - second < settings.multiple_mark_delta:
            status = "multiple_marks"
            detected = None
            confidence = max(0.0, min(1.0, best - second))
            warnings.append("multiple_marks_close_fill")
        else:
            detected = best_label
            confidence = max(0.0, min(1.0, 0.5 * best + 0.5 * (best - second) / max(best, 0.01)))
            status = "low_confidence" if confidence < settings.low_confidence_threshold else "correct"
            if status == "low_confidence":
                warnings.append("mark_confidence_below_threshold")
        expected = template.answer_key.get(q + 1) if template.answer_key else None
        is_correct = detected == expected if expected and detected else (False if expected and status != "blank" else None)
        if expected and status == "correct":
            status = "correct" if is_correct else "incorrect"
        results.append(QuestionResult(question_number=q + 1, detected_option=detected, fill_scores=scores, confidence=round(confidence, 4), status=status, is_correct=is_correct, score=1.0 if is_correct else 0.0, bounding_boxes=boxes, warnings=warnings))
    return results
